baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

# 页面底部信息配置
  [params.footer]
    enable = true   
    since = 2023
    # 公网安备信息，仅在中国使用（支持 HTML 格式）
    #gov = "<a href=\"http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=41082302411133\" target=\"_blank\" > &nbsp;豫公网安备 41082302411133号</a>"
    gov = "<a href=\"http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=41082302411133\" target=\"_blank\" > &nbsp;豫公网安备 41082302411133号</a>"
    #  ICP 备案信息，仅在中国使用（支持 HTML 格式）
    icp = "<a target=\"_blank\" rel=\"noopener\" href=\"http://beian.miit.gov.cn/\">京ICP备15015906号-6</a>"   
    siteTime =  "2023-05-13 16:35:29+08:00" # e.g. "2021-12-18T16:15:22+08:00"
  
  # 侧边栏配置
  [params.aside]
    enable = false #是否启用，false 不启用
    github = "ccfread" #github名字
    gitee = "ccfread" #gitee名字
    bilibili = "ccfread" #bilibili名字
    QQ = "ccfread" #QQ号
    weibo = "ccfread" #填写微博名字或id
    email = "ccfread" #邮箱地址
  
  # 侧边栏配置
  [params.author]
    name = "小馒头"
    discribe = "这里填写了描述的花语"
